version: '3'

services:
  app:
    build: app
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/hotel_new?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USER_NAME: root
      DB_PASSWORD: ROOT
      SC_USER_NAME: drax182
      SC_PASSWORD: x845fg4      
    restart: always
    depends_on:
      mysql:
          condition: service_healthy
  mysql:
    image: mysql:8.0.21 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_PASSWORD: ROOT
      MYSQL_DATABASE: hotel_new
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10