version: '3'

services:
  app:
    build: ejercicio
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/cursos?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USER_NAME: root
      DB_PASSWORD: 
    restart: always
    depends_on:
      mysql:
          condition: service_healthy
  mysql:
    image: mysql:8.4.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_PASSWORD: ROOT
      MYSQL_DATABASE: cursos
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10